"""Box builder for the CAD Viewer: save a box, build its parts in bounded child processes.

Where boxes live
    A local viewer keeps them in ``<root>/boxes/<name>/``. A hosted viewer (one
    that serves several signed-in accounts) gives each account its own
    ``<root>/boxes/u-<hash of its e-mail>/<name>/``; no route reaches another
    account's folder. A box folder holds ``<name>.box.json`` (the editable
    description), a generated model script per part (``<name>_base.py``,
    ``<name>_lid.py``) and the ``.step``/``.stl``/``.3mf`` those scripts build.

What is trusted
    Nothing the client sends is executed. The geometry arrives as a plan in
    ``cadgen.box_plan``'s grammar, is checked against it, and is written into the
    scripts as a literal. Each script then runs as ``python <script>`` in a child
    process -- never inside this server, which does not load the kernel -- with a
    wall-clock timeout that kills the whole process tree, CPU-time and file-size
    limits, and output captured to a size-limited file. At most ``max_builds`` run
    at once behind a bounded queue.

What a hosted viewer adds
    One active build per account, per-account daily counts of new boxes and
    builds, a daily cap on new boxes across all accounts, a disk budget per
    account, a refusal to start builds when the disk runs low, and a throwaway
    cadgen cache per build so nothing accumulates outside the box folders.
"""

from __future__ import annotations

import contextlib
import datetime as _dt
import hashlib
import json
import os
import pprint
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

from cadgen.box_plan import BOX_PART_NAMES, PlanError, normalize_box_plan

__all__ = [
    "BOXES_DIRNAME",
    "BOX_OUTPUT_CONTENT_TYPES",
    "MAX_REQUEST_BYTES",
    "BoxBuilder",
    "BoxBusy",
    "BoxError",
    "BoxLimits",
    "BoxNotFound",
    "BoxQuotaExceeded",
    "BuildResult",
    "check_box_name",
    "owner_key",
    "run_model_script",
    "script_source",
]

BOXES_DIRNAME = "boxes"
QUOTA_DIRNAME = ".box-quota"
SPEC_SUFFIX = ".box.json"
BOX_OUTPUT_CONTENT_TYPES = {"step": "application/step", "stl": "model/stl", "3mf": "model/3mf"}
MAX_REQUEST_BYTES = 1024 * 1024
# Room for a lid engraving: a drawing's contours are thousands of numbers.
MAX_SPEC_BYTES = 256 * 1024
GENERATED_MARKER = "Generated by the CAD Viewer box builder"
FINISHED_BUILD_RETENTION_SECONDS = 3600.0
_OUTPUT_TAIL_CHARS = 20_000
_ALL_ACCOUNTS_KEY = "_all"
_LOCK_STRIPES = 64

_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]{0,63}")
_RESERVED_NAMES = frozenset(
    {"con", "prn", "aux", "nul", *(f"com{i}" for i in range(1, 10)), *(f"lpt{i}" for i in range(1, 10))}
)
_ACTIVE_STATES = ("queued", "building")
_ABSOLUTE_PATH = re.compile(r"(?:[A-Za-z]:)?(?:[\\/][\w.\-]+)+[\\/]([\w.\-]+)")


# --- errors -------------------------------------------------------------------


class BoxError(ValueError):
    """A request the box builder refuses. ``code`` is stable for clients; ``status`` is HTTP."""

    status = 400
    code = "invalid"

    def __init__(self, message: str, *, code: str | None = None, status: int | None = None) -> None:
        super().__init__(message)
        if code is not None:
            self.code = code
        if status is not None:
            self.status = status


class BoxNotFound(BoxError):
    status = 404
    code = "not_found"


class BoxBusy(BoxError):
    status = 429
    code = "busy"


class BoxQuotaExceeded(BoxError):
    status = 429
    code = "quota"


# --- names and owners -----------------------------------------------------------


def check_box_name(name: object) -> str:
    text = name if isinstance(name, str) else ""
    if not _NAME.fullmatch(text) or text.lower() in _RESERVED_NAMES:
        raise BoxError(
            "box name: 1-64 Latin letters, digits, '-' or '_', starting with a letter or digit",
            code="bad_name",
        )
    return text


def owner_key(owner: str | None) -> str | None:
    """The folder name for an account; ``None`` (a local viewer) has no account folder.

    A hash, so the e-mail address itself is never written to disk."""
    if owner is None:
        return None
    email = owner.strip().lower()
    if not email or len(email) > 320:
        raise BoxError("sign in required", code="unauthorized", status=401)
    return "u-" + hashlib.sha256(email.encode("utf-8")).hexdigest()[:32]


# --- scripts ----------------------------------------------------------------------


def _function_name(name: str, part: str) -> str:
    identifier = re.sub(r"[^0-9A-Za-z_]", "_", name).lower()
    if identifier[0].isdigit():
        identifier = f"box_{identifier}"
    return f"{identifier}_{part}"


def script_source(name: str, part: str, node: dict) -> str:
    """The model script for one part: the plan as a literal, built by cadgen.box_csg."""
    function = _function_name(name, part)
    plan = pprint.pformat(node, width=100, sort_dicts=False)
    return (
        f'"""{GENERATED_MARKER}: box "{name}", part "{part}".\n'
        "\n"
        "Edit the box in the viewer's box builder; saving there rewrites this file.\n"
        "PLAN is the geometry in cadgen.box_plan's grammar.\n"
        '"""\n'
        "\n"
        "from cadgen import step, stl, threemf\n"
        "from cadgen.box_csg import shape_from_plan\n"
        "\n"
        f"PLAN = {plan}\n"
        "\n"
        "\n"
        "@threemf\n"
        "@stl\n"
        "@step\n"
        f"def {function}():\n"
        "    return shape_from_plan(PLAN)\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        f"    {function}()\n"
    )


def _write_text(path: Path, text: str) -> None:
    """Atomic replace through a uniquely named temporary: concurrent writers never share one."""
    handle, temporary = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
        os.replace(temporary, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(temporary)
        raise


def _folder_bytes(folder: Path) -> int:
    total = 0
    for dirpath, _dirnames, filenames in os.walk(folder):
        for filename in filenames:
            with contextlib.suppress(OSError):
                total += os.lstat(os.path.join(dirpath, filename)).st_size
    return total


# --- running a build ----------------------------------------------------------------


@dataclass(frozen=True)
class BuildResult:
    code: int
    output: str
    timed_out: bool = False


# Applied in the child after fork and before the script's interpreter starts, by
# exec'ing through this one-liner: rlimits survive exec, and no preexec_fn has to
# run Python between fork and exec in this multi-threaded server. -P keeps the
# box folder off sys.path.
_LIMITED_EXEC = (
    "import os, resource, sys\n"
    "cpu, size = int(sys.argv[1]), int(sys.argv[2])\n"
    "resource.setrlimit(resource.RLIMIT_CPU, (cpu, cpu))\n"
    "resource.setrlimit(resource.RLIMIT_FSIZE, (size, size))\n"
    "os.execv(sys.executable, [sys.executable, '-P', sys.argv[3]])\n"
)


def _kill_tree(process: subprocess.Popen) -> None:
    if os.name == "posix":
        with contextlib.suppress(ProcessLookupError, PermissionError):
            os.killpg(process.pid, signal.SIGKILL)
    else:
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(process.pid)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
    with contextlib.suppress(OSError):
        process.kill()


def _read_tail(log) -> str:
    size = log.seek(0, os.SEEK_END)
    log.seek(max(0, size - _OUTPUT_TAIL_CHARS * 4))
    return log.read().decode("utf-8", errors="replace")[-_OUTPUT_TAIL_CHARS:]


def run_model_script(
    script: Path,
    *,
    timeout: float,
    max_output_bytes: int,
    ephemeral_cache: bool = False,
) -> BuildResult:
    """Build one generated model script as ``python <script>`` in its own process group."""
    from cadgen.daemon.executors import worker_env

    env = worker_env()
    # One process tree per build, killable as a unit: no warm daemon worker that
    # would outlive the timeout or take jobs from other boxes.
    env["CADGEN_DAEMON"] = "0"
    with contextlib.ExitStack() as stack:
        log = stack.enter_context(tempfile.TemporaryFile())
        if ephemeral_cache:
            env["CADGEN_CACHE_DIR"] = stack.enter_context(
                tempfile.TemporaryDirectory(prefix="box-cache-", ignore_cleanup_errors=True)
            )
        popen: dict[str, Any] = {
            "cwd": script.parent,
            "env": env,
            "stdin": subprocess.DEVNULL,
            "stdout": log,
            "stderr": subprocess.STDOUT,
        }
        if os.name == "posix":
            cpu_seconds = int(timeout) + 30
            argv = [
                sys.executable, "-P", "-c", _LIMITED_EXEC,
                str(cpu_seconds), str(int(max_output_bytes)), script.name,
            ]
            popen["start_new_session"] = True
        else:
            argv = [sys.executable, "-P", script.name]
            popen["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
        process = subprocess.Popen(argv, **popen)
        timed_out = False
        try:
            process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            timed_out = True
            _kill_tree(process)
            with contextlib.suppress(subprocess.TimeoutExpired):
                process.wait(timeout=10)
        output = _read_tail(log)
    if timed_out:
        return BuildResult(-9, output, timed_out=True)
    return BuildResult(process.returncode, output)


def _failure_text(result: BuildResult, timeout: float) -> str:
    """One short line a person can read, with no server paths in it."""
    if result.timed_out:
        return f"the build took longer than {int(timeout)} s and was stopped"
    from cadgen.daemon.jobs import failure_message

    message, _ = failure_message(result.output)
    text = _ABSOLUTE_PATH.sub(r"\1", message or "the build failed").strip()
    return text[:300] or "the build failed"


# --- limits and quota ------------------------------------------------------------------


@dataclass(frozen=True)
class BoxLimits:
    max_builds: int = 2
    max_queue: int = 8
    build_timeout: float = 180.0
    max_output_bytes: int = 256 * 1024 * 1024
    # Per account per day; None means unlimited (a local viewer has no accounts).
    daily_new_boxes: int | None = None
    daily_builds: int | None = None
    # New boxes per day across every account together.
    global_daily_new_boxes: int | None = None
    # Bytes one account's boxes may occupy.
    account_max_bytes: int | None = None
    # No build starts while the data disk has less free space than this.
    min_free_bytes: int | None = None
    # A fresh cadgen cache per build, deleted afterwards.
    ephemeral_cache: bool = False
    timezone: str = "Europe/Kyiv"

    @classmethod
    def from_env(cls, *, hosted: bool, environ: dict | None = None) -> "BoxLimits":
        source = os.environ if environ is None else environ

        def read(key: str, default, cast: Callable = int):
            raw = str(source.get(key, "")).strip()
            if not raw:
                return default
            try:
                value = cast(raw)
            except ValueError:
                return default
            return None if value < 0 else value

        flag = str(source.get("CADGEN_BOX_EPHEMERAL_CACHE", "")).strip().lower()
        return cls(
            max_builds=max(1, read("CADGEN_BOX_MAX_BUILDS", 2) or 1),
            max_queue=max(0, read("CADGEN_BOX_MAX_QUEUE", 8) or 0),
            build_timeout=max(10.0, float(read("CADGEN_BOX_BUILD_TIMEOUT", 90.0 if hosted else 180.0, float) or 90.0)),
            max_output_bytes=max(1_000_000, read("CADGEN_BOX_MAX_OUTPUT_BYTES", 256 * 1024 * 1024) or 0),
            daily_new_boxes=read("CADGEN_BOX_DAILY_NEW", 1 if hosted else None),
            daily_builds=read("CADGEN_BOX_DAILY_BUILDS", 20 if hosted else None),
            global_daily_new_boxes=read("CADGEN_BOX_GLOBAL_DAILY_NEW", 500 if hosted else None),
            account_max_bytes=read("CADGEN_BOX_ACCOUNT_MAX_BYTES", 200 * 1024 * 1024 if hosted else None),
            min_free_bytes=read("CADGEN_BOX_MIN_FREE_BYTES", 10 * 1024**3 if hosted else None),
            ephemeral_cache=(flag in {"1", "true", "yes"}) if flag else hosted,
            timezone=str(source.get("CADGEN_BOX_TIMEZONE", "") or "Europe/Kyiv"),
        )


class _QuotaBook:
    """Daily counters, one small JSON file per account (and one for all accounts)."""

    def __init__(self, directory: Path, timezone: str) -> None:
        self.directory = directory
        self.timezone = timezone
        self._lock = threading.Lock()

    def today(self) -> str:
        try:
            from zoneinfo import ZoneInfo

            return _dt.datetime.now(ZoneInfo(self.timezone)).date().isoformat()
        except Exception:  # noqa: BLE001 - no tz database: fall back to UTC days
            return _dt.datetime.now(_dt.timezone.utc).date().isoformat()

    def _read(self, key: str) -> dict:
        today = self.today()
        empty = {"day": today, "newBoxes": 0, "builds": 0}
        try:
            stored = json.loads((self.directory / f"{key}.json").read_text(encoding="utf-8", errors="replace"))
        except FileNotFoundError:
            return empty
        except (OSError, json.JSONDecodeError):
            # Unreadable counters must not read as "nothing used yet".
            raise BoxBusy("usage limits are unavailable right now; try again later", code="quota_unavailable") from None
        if not isinstance(stored, dict) or stored.get("day") != today:
            return empty
        try:
            return {"day": today, "newBoxes": int(stored.get("newBoxes", 0)), "builds": int(stored.get("builds", 0))}
        except (TypeError, ValueError):
            raise BoxBusy("usage limits are unavailable right now; try again later", code="quota_unavailable") from None

    def usage(self, key: str) -> dict:
        with self._lock:
            return self._read(key)

    def record(self, key: str, *, new_box: bool) -> dict:
        with self._lock:
            usage = self._read(key)
            usage["builds"] += 1
            if new_box:
                usage["newBoxes"] += 1
            self.directory.mkdir(parents=True, exist_ok=True)
            _write_text(self.directory / f"{key}.json", json.dumps(usage) + "\n")
            return usage


# --- the builder ---------------------------------------------------------------------


class _Build:
    __slots__ = ("state", "parts", "started_at", "finished_at", "rerun", "owner", "name")

    def __init__(self, owner: str | None = None, name: str = "") -> None:
        self.owner = owner
        self.name = name
        self.state = "queued"
        self.parts: dict[str, dict] = {}
        self.started_at = time.time()
        self.finished_at: float | None = None
        self.rerun: list[tuple[str, Path]] | None = None


Runner = Callable[..., BuildResult]


class BoxBuilder:
    """Saved boxes under ``<root>/boxes`` and the builds of their parts.

    Every method takes ``owner``: ``None`` for a local viewer, the signed-in
    account's e-mail for a hosted one."""

    def __init__(
        self,
        root: str,
        *,
        limits: BoxLimits | None = None,
        runner: Runner | None = None,
        expose_paths: bool = True,
        observer: Callable[..., None] | None = None,
    ) -> None:
        self.root = Path(root).resolve()
        self.limits = limits or BoxLimits()
        # runner(script, *, timeout, max_output_bytes, ephemeral_cache) -> BuildResult.
        self._runner = runner or run_model_script
        self.expose_paths = expose_paths
        # observer(event, owner, **fields): what accounts do, for a hosted viewer's analytics.
        self._observer = observer
        self._lock = threading.Lock()
        self._builds: dict[tuple[str | None, str], _Build] = {}
        # A fixed set of locks, picked by hash: no per-name lock objects to pile up.
        self._stripes = tuple(threading.Lock() for _ in range(_LOCK_STRIPES))
        self._slots = threading.BoundedSemaphore(self.limits.max_builds)
        self._quota = _QuotaBook(self.root / QUOTA_DIRNAME, self.limits.timezone)

    # --- places --------------------------------------------------------

    def _space(self, owner: str | None) -> Path:
        key = owner_key(owner)
        base = self.root / BOXES_DIRNAME
        return base if key is None else base / key

    def _box_dir(self, name: str, owner: str | None) -> Path:
        space = self._space(owner)
        directory = (space / name).resolve()
        if directory.parent != space.resolve() or not directory.is_relative_to(self.root):
            raise BoxError("box folder escapes the served directory")
        return directory

    @contextlib.contextmanager
    def _locked(self, *keys: tuple):
        """Hold the stripes for ``keys``, always in index order, so two savers never deadlock."""
        indexes = sorted({hash(key) % _LOCK_STRIPES for key in keys})
        with contextlib.ExitStack() as stack:
            for index in indexes:
                stack.enter_context(self._stripes[index])
            yield

    # --- reading -------------------------------------------------------

    def outputs(self, name: str, owner: str | None = None) -> list[dict]:
        directory = self._space(owner) / name
        found = []
        for part in BOX_PART_NAMES:
            for fmt in BOX_OUTPUT_CONTENT_TYPES:
                path = directory / f"{name}_{part}.{fmt}"
                if not path.is_file():
                    continue
                stat = path.stat()
                item = {
                    "part": part,
                    "format": fmt,
                    "file": path.relative_to(self.root).as_posix(),
                    "size": stat.st_size,
                    "modifiedAt": stat.st_mtime,
                }
                if self.expose_paths:
                    item["path"] = str(path)
                found.append(item)
        return found

    def output_file(self, name: object, part: object, fmt: object, owner: str | None = None) -> Path:
        name = check_box_name(name)
        if part not in BOX_PART_NAMES or fmt not in BOX_OUTPUT_CONTENT_TYPES:
            raise BoxError("unknown part or format")
        path = self._box_dir(name, owner) / f"{name}_{part}.{fmt}"
        if not path.is_file():
            raise BoxNotFound("no such file")
        return path

    def list_boxes(self, owner: str | None = None) -> dict:
        space = self._space(owner)
        boxes = []
        if space.is_dir():
            for directory in space.iterdir():
                if not directory.is_dir() or directory.name.startswith("."):
                    continue
                try:
                    name = check_box_name(directory.name)
                except BoxError:
                    continue
                spec_path = directory / f"{name}{SPEC_SUFFIX}"
                if spec_path.is_file():
                    boxes.append({"name": name, "updatedAt": spec_path.stat().st_mtime})
        boxes.sort(key=lambda box: box["updatedAt"], reverse=True)
        return {"boxes": boxes, **self._quota_payload(owner)}

    def load(self, name: object, owner: str | None = None) -> dict:
        name = check_box_name(name)
        spec_path = self._box_dir(name, owner) / f"{name}{SPEC_SUFFIX}"
        if not spec_path.is_file():
            raise BoxNotFound(f"no saved box named {name}")
        try:
            document = json.loads(spec_path.read_text(encoding="utf-8", errors="replace"))
        except (OSError, json.JSONDecodeError):
            raise BoxError(f"{spec_path.name} is not readable") from None
        spec = document.get("spec") if isinstance(document, dict) else None
        if not isinstance(spec, dict):
            raise BoxError(f"{spec_path.name} holds no box spec")
        return {"spec": spec, **self.status(name, owner)}

    def status(self, name: object, owner: str | None = None) -> dict:
        name = check_box_name(name)
        key = owner_key(owner)
        with self._lock:
            build = self._builds.get((key, name))
            snapshot = None
            if build is not None and build.parts:
                snapshot = {
                    "state": build.state,
                    "parts": {part: dict(info) for part, info in build.parts.items()},
                    "startedAt": build.started_at,
                    "finishedAt": build.finished_at,
                }
        return {"name": name, "build": snapshot, "outputs": self.outputs(name, owner), **self._quota_payload(owner)}

    def _quota_payload(self, owner: str | None) -> dict:
        key = owner_key(owner)
        if key is None:
            return {}
        try:
            usage = self._quota.usage(key)
        except BoxError:
            usage = {"day": self._quota.today(), "newBoxes": None, "builds": None}
        return {
            "quota": {
                **usage,
                "dailyNewBoxes": self.limits.daily_new_boxes,
                "dailyBuilds": self.limits.daily_builds,
            }
        }

    def wait(self, name: str, owner: str | None = None, timeout: float | None = None) -> bool:
        """For tests and callers that must block: True once no build of ``name`` is active."""
        build_key = (owner_key(owner), name)
        deadline = None if timeout is None else time.monotonic() + timeout
        while True:
            with self._lock:
                build = self._builds.get(build_key)
                if build is None or build.state not in _ACTIVE_STATES:
                    return True
            if deadline is not None and time.monotonic() > deadline:
                return False
            time.sleep(0.02)

    # --- saving --------------------------------------------------------

    def save(self, name: object, body: bytes, owner: str | None = None) -> dict:
        """Write the box and queue the build of its parts; returns the status at once."""
        name = check_box_name(name)
        key = owner_key(owner)
        if len(body) > MAX_REQUEST_BYTES:
            raise BoxError("box request is too large", code="too_large", status=413)
        try:
            payload = json.loads(body.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            raise BoxError("box request is not JSON") from None
        if not isinstance(payload, dict) or not isinstance(payload.get("spec"), dict):
            raise BoxError("box request: expected {spec, plan}")
        document = {"format": "cadgen-box", "version": 1, "name": name, "spec": payload["spec"]}
        spec_text = json.dumps(document, ensure_ascii=False, indent=2) + "\n"
        if len(spec_text.encode("utf-8")) > MAX_SPEC_BYTES:
            raise BoxError("box description is too large", code="too_large", status=413)
        try:
            plan = normalize_box_plan(payload.get("plan"))
        except PlanError as error:
            raise BoxError(str(error), code="bad_plan") from None

        directory = self._box_dir(name, owner)
        build_key = (key, name)
        # The account's lock makes "check the quota, then record it" one step, so
        # parallel saves of different new boxes cannot all pass the check.
        with self._locked(("account", key), ("box", key, name)):
            is_new = not (directory / f"{name}{SPEC_SUFFIX}").is_file()
            self._check_quota(key, is_new=is_new)
            self._check_space(owner, key)
            reservation = self._reserve(build_key, owner)
            try:
                directory.mkdir(parents=True, exist_ok=True)
                _write_text(directory / f"{name}{SPEC_SUFFIX}", spec_text)
                scripts: list[tuple[str, Path]] = []
                for part in BOX_PART_NAMES:
                    node = plan[part]
                    if node is None:
                        self._remove_part(directory, name, part)
                        continue
                    script = directory / f"{name}_{part}.py"
                    _write_text(script, script_source(name, part, node))
                    scripts.append((part, script))
                if key is not None:
                    self._quota.record(key, new_box=is_new)
                    if is_new and self.limits.global_daily_new_boxes is not None:
                        self._quota.record(_ALL_ACCOUNTS_KEY, new_box=True)
            except BaseException:
                self._release(build_key, reservation)
                raise
            self._launch(build_key, scripts, reservation)
        self._emit("save", owner, box=name, new=is_new)
        return self.status(name, owner)

    def _check_quota(self, key: str | None, *, is_new: bool) -> None:
        if key is None:
            return
        limits = self.limits
        usage = self._quota.usage(key)
        if is_new and limits.daily_new_boxes is not None and usage["newBoxes"] >= limits.daily_new_boxes:
            raise BoxQuotaExceeded(f"daily limit of {limits.daily_new_boxes} new box(es) reached", code="quota_new")
        if limits.daily_builds is not None and usage["builds"] >= limits.daily_builds:
            raise BoxQuotaExceeded(f"daily limit of {limits.daily_builds} builds reached", code="quota_builds")
        if is_new and limits.global_daily_new_boxes is not None:
            if self._quota.usage(_ALL_ACCOUNTS_KEY)["newBoxes"] >= limits.global_daily_new_boxes:
                raise BoxQuotaExceeded("the service has made all its new boxes for today", code="quota_global")

    def _check_space(self, owner: str | None, key: str | None) -> None:
        limits = self.limits
        if limits.min_free_bytes is not None:
            try:
                free = shutil.disk_usage(self.root).free
            except OSError:
                free = 0
            if free < limits.min_free_bytes:
                raise BoxBusy("the server is short of disk space for new builds", code="disk_full")
        if key is not None and limits.account_max_bytes is not None:
            if _folder_bytes(self._space(owner)) > limits.account_max_bytes:
                raise BoxQuotaExceeded("this account's boxes use all of their space", code="quota_disk")

    def _reserve(self, build_key: tuple[str | None, str], owner: str | None = None) -> str:
        """Take a place for this build atomically: ``"new"``, or ``"rerun"`` of an active one."""
        with self._lock:
            self._forget_finished_builds()
            current = self._builds.get(build_key)
            if current is not None and current.state in _ACTIVE_STATES:
                return "rerun"
            active = [other for other, build in self._builds.items() if build.state in _ACTIVE_STATES]
            if build_key[0] is not None and any(other[0] == build_key[0] for other in active):
                raise BoxBusy("your previous box is still building", code="busy_account")
            if len(active) >= self.limits.max_builds + self.limits.max_queue:
                raise BoxBusy("the build queue is full; try again in a minute")
            self._builds[build_key] = _Build(owner=owner, name=build_key[1])
            return "new"

    def _release(self, build_key: tuple[str | None, str], reservation: str) -> None:
        if reservation != "new":
            return
        with self._lock:
            build = self._builds.get(build_key)
            if build is not None and not build.parts:
                del self._builds[build_key]

    def _launch(self, build_key: tuple[str | None, str], scripts: list[tuple[str, Path]], reservation: str) -> None:
        with self._lock:
            build = self._builds[build_key]
            if reservation == "rerun" and build.state in _ACTIVE_STATES:
                # The scripts on disk are already the new ones; build them again
                # once the running jobs finish, so the last save always wins.
                build.rerun = scripts
                return
            build.state = "queued"
            build.started_at = time.time()
            build.finished_at = None
            build.parts = {part: {"state": "queued", "error": ""} for part, _ in scripts}
            if not scripts:
                build.state = "done"
                build.finished_at = time.time()
                return
        threading.Thread(
            target=self._run,
            args=(build, scripts),
            name=f"cadgen-box-build-{build_key[1]}",
            daemon=True,
        ).start()

    def _remove_part(self, directory: Path, name: str, part: str) -> None:
        """A part the box no longer has (a lid switched off): drop what WE generated for it.

        Outputs go only together with a script that carries our marker, so a
        hand-made file of the same name is never touched."""
        script = directory / f"{name}_{part}.py"
        try:
            generated = script.is_file() and GENERATED_MARKER in script.read_text(
                encoding="utf-8", errors="replace"
            )[:400]
        except OSError:
            generated = False
        if not generated:
            return
        script.unlink()
        for fmt in BOX_OUTPUT_CONTENT_TYPES:
            output = directory / f"{name}_{part}.{fmt}"
            if output.is_file():
                output.unlink()

    # --- builds --------------------------------------------------------

    def _forget_finished_builds(self) -> None:
        horizon = time.time() - FINISHED_BUILD_RETENTION_SECONDS
        for build_key, build in list(self._builds.items()):
            if build.state not in _ACTIVE_STATES and (build.finished_at or 0) < horizon:
                del self._builds[build_key]

    def _run(self, build: _Build, scripts: list[tuple[str, Path]]) -> None:
        while True:
            with self._slots:
                with self._lock:
                    build.state = "building"
                    build.started_at = time.time()
                    for info in build.parts.values():
                        info["state"] = "building"
                timed_out = False
                for part, script in scripts:
                    try:
                        result = self._runner(
                            script,
                            timeout=self.limits.build_timeout,
                            max_output_bytes=self.limits.max_output_bytes,
                            ephemeral_cache=self.limits.ephemeral_cache,
                        )
                    except Exception as error:  # noqa: BLE001 - a failure to start is a part error
                        result = BuildResult(1, f"{type(error).__name__}: {error}")
                    timed_out = timed_out or result.timed_out
                    if result.code == 0:
                        self._set_part(build, part, "done", "")
                    else:
                        self._set_part(build, part, "error", _failure_text(result, self.limits.build_timeout))
            with self._lock:
                pass_failed = any(info["state"] == "error" for info in build.parts.values())
                pass_seconds = round(time.time() - build.started_at, 2)
            self._emit(
                "build",
                build.owner,
                box=build.name,
                state="error" if pass_failed else "done",
                seconds=pass_seconds,
                timedOut=timed_out,
            )
            with self._lock:
                if build.rerun is not None:
                    scripts, build.rerun = build.rerun, None
                    build.state = "queued"
                    build.parts = {part: {"state": "queued", "error": ""} for part, _ in scripts}
                    continue
                failed = any(info["state"] == "error" for info in build.parts.values())
                build.state = "error" if failed else "done"
                build.finished_at = time.time()
                return

    def _emit(self, event: str, owner: str | None, **fields) -> None:
        if self._observer is None or owner is None:
            return
        try:
            self._observer(event, owner, **fields)
        except Exception:  # noqa: BLE001 - analytics never breaks a save or a build
            pass

    def activity(self) -> dict:
        """Builds running and waiting right now, against the limits."""
        with self._lock:
            states = [build.state for build in self._builds.values()]
        return {
            "building": states.count("building"),
            "queued": states.count("queued"),
            "maxBuilds": self.limits.max_builds,
            "maxQueue": self.limits.max_queue,
        }

    def account_usage(self, owner: str) -> dict:
        """How many boxes an account keeps and how many bytes they take."""
        space = self._space(owner)
        if not space.is_dir():
            return {"boxes": 0, "bytes": 0}
        boxes = sum(
            1 for directory in space.iterdir()
            if directory.is_dir() and (directory / f"{directory.name}{SPEC_SUFFIX}").is_file()
        )
        return {"boxes": boxes, "bytes": _folder_bytes(space)}

    def _set_part(self, build: _Build, part: str, state: str, error: str) -> None:
        with self._lock:
            build.parts[part] = {"state": state, "error": error}
